services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    image: shiny:latest
    container_name: shiny
    ports:
      - "3838:3838"
    volumes:
      - ${DATA_DIR:-./data}:/srv/shiny-server/data
      - ${BACKUP_DIR:-./backup_data}:/srv/shiny-server/backup_data
    group_add:
      - "${DATA_GID:-100}"
      - "${BACKUP_GID:-998}"
    restart: unless-stopped