---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(fig.width=30, fig.height=20, out.width = "100%", out.height="1000px", dpi=200)
rm(list = ls())

library(ggplot2)
library(ggthemes)
library(tidyr)
library(reshape2)
library(tidyverse)
library(readxl)
library(dplyr)
library(plotly)
```

## Data cleaning

```{r cars, message=FALSE, warning=FALSE}
path = "data/2017"
temp <- list.files(path=path)
data1 <- read_excel(paste(path,temp[1], sep="/"), sheet = "Student", skip = 1)
data2 <- read_csv(paste(path,temp[2], sep="/"))
```

```{r}
tag <- data2 %>% 
  select(`ID`, `UoA ID`, `UoA UPI`, `Tags`)
head(tag,5)
```

```{r}
# Participant programme
partProg <- tag$Tags %>% 
  strsplit(., ",") %>% 
  setNames(tag$`UoA ID`) %>% 
  melt(value.name = "programme")

colnames(partProg) <- c("programme", "ID")

head(partProg,5)
```

```{r message=FALSE, warning=FALSE}
#TODO: Active in Programme?
partInfo<- data1 %>% 
  select(`ID`, `Acad Prog`, `Status`, `Descriptio`, `Acad Plan`, `Plan Description`, `Owner of Major/Spec/Module`)

head(partInfo,5)
```

```{r outer-join}
# Outer join two tables
df <- merge(x=partProg, y=partInfo, by="ID", all.x = TRUE)
head(df,5)
```


```{r filter-non-student}
# Filter out non-students
df_stud <- df %>% 
  filter(!is.na(`Acad Prog`))

head(df_stud,10)
```

```{r cleaning-year, message=FALSE, warning=FALSE}
# Only select specific year
df_stud <- df_stud %>% 
  mutate(year=substring(`programme`,0,4), programme=substring(`programme`,6)) %>% 
  filter(year=="2017")

head(df_stud,5)
```

```{r faculty-split-overall}
df_stud %>% 
  group_by(`Owner of Major/Spec/Module`) %>% 
  summarise(count=n()) %>% 
  ggplot() +
  geom_bar(aes(x=reorder(`Owner of Major/Spec/Module`, count), count, fill=count), stat="identity") +
  guides(fill=FALSE) +
  coord_flip() +
  ggtitle("Faculty split overall") +
  theme_hc() + 
  scale_fill_continuous_tableau() + labs(x="")
```

```{r programme-split-overal, fig.fullwidth=TRUE, fig.fullheight=TRUE}
# Lollipop chart
df_stud %>% 
  group_by(`programme`) %>% 
  summarise(count=n()) %>% 
  filter(!`programme` %in% c("CIE Participant", "Velocity Participant", "Unleash Space Participant", "Unleash Space Access", "Equipment Training Participant" )) %>% 
  arrange(count) %>% 
  mutate(programme = factor(`programme`, levels=.$programme)) %>% 
  ggplot(aes(count, programme, label=count, fill=count, color=-count)) +
  geom_segment(aes(x=0, y=programme, xend=count, yend=programme)) +
  geom_point(size=5) +
  guides(fill=FALSE, color=FALSE) +
  ggtitle("Programme split overall") +
  theme_minimal() + 
  scale_fill_continuous_tableau() + labs(x="", y="")
  #geom_text(nudge_x=10)

# Bar chart
df_stud %>% 
  group_by(`programme`) %>% 
  summarise(count=n()) %>% 
  filter(!`programme` %in% c("CIE Participant", "Velocity Participant", "Unleash Space Participant", "Unleash Space Access", "Equipment Training Participant" )) %>% 
  arrange(count) %>% 
  mutate(programme = factor(`programme`, levels=.$programme)) %>% 
  ggplot(aes(programme, count, label=count, fill=count)) +
  geom_bar(stat="identity") +
  coord_flip() +
  guides(fill=FALSE, color=FALSE) +
  ggtitle("Programme split overall") +
  theme_minimal() + 
  scale_fill_continuous_tableau() + labs(x="", y="")

```

```{r programme-by-faculty}
# Create dataframe for heatmap
df_stud %>% 
  select(`programme`, `Owner of Major/Spec/Module`) %>% 
  filter(!`programme` %in% c("CIE Participant", "Velocity Participant", "Unleash Space Participant", "Unleash Space Access", "Equipment Training Participant" )) %>%
  group_by(`programme`,`Owner of Major/Spec/Module`) %>% 
  summarise(count=n()) %>%
  complete(`Owner of Major/Spec/Module` = unique(df_stud$`Owner of Major/Spec/Module`)) %>% 
  ggplot(aes(`Owner of Major/Spec/Module`, `programme`)) + 
  geom_tile(aes(fill=count), colour="grey97") +
  guides(color=FALSE) +
  ggtitle("Programme split overall") +
  scale_fill_gradient_tableau(na.value = "white") +
  scale_x_discrete(position="top") +
  #scale_fill_gradient(low="white", high = "steelblue", na.value="grey80") +
  coord_fixed(ratio=.25) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=0)) +
  labs(x="", y="")
  
```
