run_as shiny;

server {
  listen 3838;

  # Explicitly map dashboard app route.
  location /cie-dashboards {
    app_dir /srv/shiny-server/cie-dashboards;
    log_dir /var/log/shiny-server;
  }

  # Explicitly map uploads app route.
  location /cie-uploads {
    app_dir /srv/shiny-server/cie-uploads;
    log_dir /var/log/shiny-server;
  }

  # Keep root browsable for static files and directory index.
  location / {
    site_dir /srv/shiny-server;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}